### ISSUE TITLE
Feature request: Cast response.expires_in and response.refresh_token_expires_in to numbers if they are strings 

### ISSUE THREAD

**Issue by LazarescuAlexandru** [soofstad/react-oauth2-pkce#111]
## Steps To Reproduce

If the response contains the expires_in and refresh_token_expires_in as string values, the tokens are immediately considered expired.

## The current behavior
The calculation of the expiration time for the access_token and refresh_token are wrong, they are set to now.

## The expected behavior
By modifying the function to calculate the expiration time, we should be able to correctly set the token expiration time:
In the timeUtils.js line 5:

<details><summary>Current implementation</summary>

https://github.com/soofstad/react-oauth2-pkce/blob/6e7f5efdf6ce9cc46e900638e51b581d4310bbaa/src/timeUtils.ts#L5

</details> 

```ts
// proposed solution
const epochAtSecondsFromNow = (secondsFromNow) => Math.round(Date.now() / 1000 + Number(secondsFromNow));
//                                                                               ^^^^^^               ^

```

**Comment by soofstad** [comment]
Thanks for reporting :+1: 

First of all, if the response has the keys in question as strings instead of integers, thats a bug in the server's implementation of the protocol (see https://www.rfc-editor.org/rfc/rfc6749.html#appendix-A.14).

Even so, trying to convert the recived value to a number is an easy fix we can do to help compatability with badly behaved server.
