### ISSUE TITLE
Feature: Broader assumptions on failed refresh requests

### ISSUE THREAD

**Issue by soofstad** [soofstad/react-oauth2-pkce#38]
Failed refresh requests are not always identified to be caused by an expired refresh_token.

The way this is handled today is too brittle, and requires manually maintaining a list of known error responses from all possible authentication servers.

Suggestion:
Make a broader assumption like if the refresh request fails with a "400" (40x?) status code, that it's caused by an expired refresh_token.

**Comment by sebastianvitterso** [comment]
I'm gonna vote against a general 40x check at least. A 404 should not happen if the refresh token being expired, and the same applies to 403. I'll accept arguments that 401 might be ok, since technically you're no longer authenticated when this happens, but a 400 makes much more sense.

Still... we're working with a plethora of OAuth-providers, so maybe we can start with 400 and see if anyone creates issues that their providers uses 40x, and then add one by one?

**Comment by soofstad** [comment]
@prabhurajshell You should not have to check for expiry, not do a manual refresh.
The library will refresh the token in the background as long as the refresh_token is valid. When the refresh_token expires, it will trigger the `onRefreshTokenExpire`-event which you can handle. Usually by doing a page refresh, triggering a new login.
